// resources/js/Pages/Marketing/Dashboard.vue
<template>
  <AppLayout title="Marketing Digital">
    <template #header>
      <h2 class="font-semibold text-xl text-gray-800 leading-tight">
        Marketing Digital - Tableau de Bord
      </h2>
    </template>

    <div class="py-12">
      <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
        <!-- Statistiques Principales -->
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
          <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg p-6">
            <div class="flex items-center">
              <div class="flex-shrink-0">
                <div class="w-8 h-8 bg-blue-500 rounded-md flex items-center justify-center">
                  <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z"></path>
                  </svg>
                </div>
              </div>
              <div class="ml-4">
                <div class="text-sm font-medium text-gray-500">Total Clients</div>
                <div class="text-2xl font-semibold text-gray-900">{{ stats.totalClients }}</div>
              </div>
            </div>
          </div>

          <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg p-6">
            <div class="flex items-center">
              <div class="flex-shrink-0">
                <div class="w-8 h-8 bg-green-500 rounded-md flex items-center justify-center">
                  <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5.882V19.24a1.76 1.76 0 01-3.417.592l-2.147-6.15M18 13a3 3 0 100-6M5.436 13.683A4.001 4.001 0 017 6h1.832c4.1 0 7.625-1.234 9.168-3v14c-1.543-1.766-5.067-3-9.168-3H7a3.988 3.988 0 01-1.564-.317z"></path>
                  </svg>
                </div>
              </div>
              <div class="ml-4">
                <div class="text-sm font-medium text-gray-500">Campagnes Actives</div>
                <div class="text-2xl font-semibold text-gray-900">{{ stats.activeCampaigns }}</div>
              </div>
            </div>
          </div>

          <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg p-6">
            <div class="flex items-center">
              <div class="flex-shrink-0">
                <div class="w-8 h-8 bg-purple-500 rounded-md flex items-center justify-center">
                  <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z"></path>
                  </svg>
                </div>
              </div>
              <div class="ml-4">
                <div class="text-sm font-medium text-gray-500">Messages Envoyés</div>
                <div class="text-2xl font-semibold text-gray-900">{{ stats.totalMessages }}</div>
              </div>
            </div>
          </div>

          <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg p-6">
            <div class="flex items-center">
              <div class="flex-shrink-0">
                <div class="w-8 h-8 bg-yellow-500 rounded-md flex items-center justify-center">
                  <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"></path>
                  </svg>
                </div>
              </div>
              <div class="ml-4">
                <div class="text-sm font-medium text-gray-500">Automatisations</div>
                <div class="text-2xl font-semibold text-gray-900">{{ stats.activeAutomations }}</div>
              </div>
            </div>
          </div>
        </div>

        <!-- Graphiques et Métriques -->
        <div class="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-8">
          <!-- Graphique des Messages -->
          <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg p-6">
            <h3 class="text-lg font-medium text-gray-900 mb-4">Messages par Jour (7 derniers jours)</h3>
            <div class="h-64 flex items-end justify-between">
              <div v-for="(day, index) in stats.messagesByDay" :key="index" class="flex flex-col items-center">
                <div class="text-xs text-gray-500 mb-2">{{ day.date }}</div>
                <div class="w-8 bg-blue-500 rounded-t" :style="{ height: (day.count / stats.maxMessages * 200) + 'px' }"></div>
                <div class="text-xs text-gray-700 mt-1">{{ day.count }}</div>
              </div>
            </div>
          </div>

          <!-- Taux de Livraison -->
          <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg p-6">
            <h3 class="text-lg font-medium text-gray-900 mb-4">Taux de Livraison</h3>
            <div class="space-y-4">
              <div class="flex items-center justify-between">
                <span class="text-sm text-gray-600">Livrés</span>
                <span class="text-sm font-medium text-gray-900">{{ stats.deliveryRate.delivered }}%</span>
              </div>
              <div class="w-full bg-gray-200 rounded-full h-2">
                <div class="bg-green-500 h-2 rounded-full" :style="{ width: stats.deliveryRate.delivered + '%' }"></div>
              </div>
              
              <div class="flex items-center justify-between">
                <span class="text-sm text-gray-600">Lus</span>
                <span class="text-sm font-medium text-gray-900">{{ stats.deliveryRate.read }}%</span>
              </div>
              <div class="w-full bg-gray-200 rounded-full h-2">
                <div class="bg-blue-500 h-2 rounded-full" :style="{ width: stats.deliveryRate.read + '%' }"></div>
              </div>
            </div>
          </div>
        </div>

        <!-- Actions Rapides -->
        <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg p-6 mb-8">
          <h3 class="text-lg font-medium text-gray-900 mb-4">Actions Rapides</h3>
          <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
            <Link :href="route('marketing.clients.create')" class="flex items-center p-4 border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors">
              <div class="w-10 h-10 bg-blue-100 rounded-lg flex items-center justify-center mr-3">
                <svg class="w-5 h-5 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path>
                </svg>
              </div>
              <div>
                <div class="font-medium text-gray-900">Nouveau Client</div>
                <div class="text-sm text-gray-500">Ajouter un client</div>
              </div>
            </Link>

            <Link :href="route('marketing.campaigns.create')" class="flex items-center p-4 border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors">
              <div class="w-10 h-10 bg-green-100 rounded-lg flex items-center justify-center mr-3">
                <svg class="w-5 h-5 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5.882V19.24a1.76 1.76 0 01-3.417.592l-2.147-6.15M18 13a3 3 0 100-6M5.436 13.683A4.001 4.001 0 017 6h1.832c4.1 0 7.625-1.234 9.168-3v14c-1.543-1.766-5.067-3-9.168-3H7a3.988 3.988 0 01-1.564-.317z"></path>
                </svg>
              </div>
              <div>
                <div class="font-medium text-gray-900">Nouvelle Campagne</div>
                <div class="text-sm text-gray-500">Créer une campagne</div>
              </div>
            </Link>

            <Link :href="route('marketing.flyers.create')" class="flex items-center p-4 border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors">
              <div class="w-10 h-10 bg-purple-100 rounded-lg flex items-center justify-center mr-3">
                <svg class="w-5 h-5 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"></path>
                </svg>
              </div>
              <div>
                <div class="font-medium text-gray-900">Nouveau Flyer</div>
                <div class="text-sm text-gray-500">Créer un flyer</div>
              </div>
            </Link>

            <Link :href="route('marketing.automations.create')" class="flex items-center p-4 border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors">
              <div class="w-10 h-10 bg-yellow-100 rounded-lg flex items-center justify-center mr-3">
                <svg class="w-5 h-5 text-yellow-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"></path>
                </svg>
              </div>
              <div>
                <div class="font-medium text-gray-900">Nouvelle Automatisation</div>
                <div class="text-sm text-gray-500">Créer une règle</div>
              </div>
            </Link>
          </div>
        </div>

        <!-- Activités Récentes -->
        <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg p-6">
          <h3 class="text-lg font-medium text-gray-900 mb-4">Activités Récentes</h3>
          <div class="space-y-4">
            <div v-for="activity in recentActivities" :key="activity.id" class="flex items-start space-x-3 p-3 rounded-lg hover:bg-gray-50">
              <div class="flex-shrink-0">
                <div class="w-8 h-8 rounded-full flex items-center justify-center" :class="getActivityIconClass(activity.type)">
                  <svg class="w-4 h-4 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path v-if="activity.type === 'message'" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z"></path>
                    <path v-else-if="activity.type === 'campaign'" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5.882V19.24a1.76 1.76 0 01-3.417.592l-2.147-6.15M18 13a3 3 0 100-6M5.436 13.683A4.001 4.001 0 017 6h1.832c4.1 0 7.625-1.234 9.168-3v14c-1.543-1.766-5.067-3-9.168-3H7a3.988 3.988 0 01-1.564-.317z"></path>
                    <path v-else-if="activity.type === 'automation'" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"></path>
                    <path v-else stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                  </svg>
                </div>
              </div>
              <div class="flex-1 min-w-0">
                <p class="text-sm text-gray-900">{{ activity.description }}</p>
                <p class="text-xs text-gray-500">{{ formatDate(activity.created_at) }}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </AppLayout>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { Link } from '@inertiajs/vue3'
import AppLayout from '@/Layouts/AppLayout.vue'

const props = defineProps({
  stats: {
    type: Object,
    default: () => ({
      totalClients: 0,
      activeCampaigns: 0,
      totalMessages: 0,
      activeAutomations: 0,
      messagesByDay: [],
      maxMessages: 0,
      deliveryRate: {
        delivered: 0,
        read: 0
      }
    })
  },
  recentActivities: {
    type: Array,
    default: () => []
  }
})

const getActivityIconClass = (type) => {
  const classes = {
    message: 'bg-blue-500',
    campaign: 'bg-green-500',
    automation: 'bg-yellow-500',
    default: 'bg-gray-500'
  }
  return classes[type] || classes.default
}

const formatDate = (date) => {
  return new Date(date).toLocaleDateString('fr-FR', {
    day: 'numeric',
    month: 'short',
    hour: '2-digit',
    minute: '2-digit'
  })
}

onMounted(() => {
  // Charger les données si nécessaire
})
</script>

// resources/js/Pages/Dashboard.tsx
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head } from '@inertiajs/react';
import { PageProps } from '@/types';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer, LineChart, Line } from 'recharts';

interface DashboardProps extends PageProps {
    stats: {
        totalClients: number;
        totalMessages: number;
        totalCampaigns: number;
        messagesSentToday: number;
        messagesSentThisMonth: number;
        deliveryRate: number;
        monthlyStats: Array<{
            month: string;
            messages: number;
            campaigns: number;
        }>;
        categoryDistribution: Array<{
            name: string;
            count: number;
        }>;
    };
}

export default function Dashboard({ auth, stats }: DashboardProps) {
    return (
        <AuthenticatedLayout
            user={auth.user}
            header={<h2 className="font-playfair text-xl font-semibold leading-tight text-gray-800">Tableau de Bord</h2>}
        >
            <Head title="Tableau de Bord" />

            <div className="py-12">
                <div className="mx-auto max-w-7xl sm:px-6 lg:px-8">
                    {/* Stats Cards */}
                    <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
                        <div className="overflow-hidden rounded-lg bg-white p-6 shadow-lg">
                            <div className="flex items-center">
                                <div className="flex h-12 w-12 items-center justify-center rounded-full bg-violet-100">
                                    <svg className="h-6 w-6 text-violet-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
                                    </svg>
                                </div>
                                <div className="ml-4">
                                    <h3 className="font-montserrat text-sm font-medium text-gray-500">Total Clients</h3>
                                    <p className="font-playfair text-2xl font-semibold text-gray-900">{stats.totalClients}</p>
                                </div>
                            </div>
                        </div>

                        <div className="overflow-hidden rounded-lg bg-white p-6 shadow-lg">
                            <div className="flex items-center">
                                <div className="flex h-12 w-12 items-center justify-center rounded-full bg-indigo-100">
                                    <svg className="h-6 w-6 text-indigo-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 10h.01M12 10h.01M16 10h.01M9 16H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-5l-5 5v-5z" />
                                    </svg>
                                </div>
                                <div className="ml-4">
                                    <h3 className="font-montserrat text-sm font-medium text-gray-500">Messages Envoyés (Aujourd'hui)</h3>
                                    <p className="font-playfair text-2xl font-semibold text-gray-900">{stats.messagesSentToday}</p>
                                </div>
                            </div>
                        </div>

                        <div className="overflow-hidden rounded-lg bg-white p-6 shadow-lg">
                            <div className="flex items-center">
                                <div className="flex h-12 w-12 items-center justify-center rounded-full bg-violet-100">
                                    <svg className="h-6 w-6 text-violet-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M11 5.882V19.24a1.76 1.76 0 01-3.417.592l-2.147-6.15M18 13a3 3 0 100-6M5.436 13.683A4.001 4.001 0 017 6h1.832c4.1 0 7.625-1.234 9.168-3v14c-1.543-1.766-5.067-3-9.168-3H7a3.988 3.988 0 01-1.564-.317z" />
                                    </svg>
                                </div>
                                <div className="ml-4">
                                    <h3 className="font-montserrat text-sm font-medium text-gray-500">Campagnes Actives</h3>
                                    <p className="font-playfair text-2xl font-semibold text-gray-900">{stats.totalCampaigns}</p>
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* Charts */}
                    <div className="mt-8 grid grid-cols-1 gap-8 lg:grid-cols-2">
                        {/* Monthly Messages Chart */}
                        <div className="overflow-hidden rounded-lg bg-white p-6 shadow-lg">
                            <h3 className="font-playfair text-lg font-semibold text-gray-900">Activité Mensuelle</h3>
                            <div className="mt-4 h-80">
                                <ResponsiveContainer width="100%" height="100%">
                                    <LineChart data={stats.monthlyStats}>
                                        <CartesianGrid strokeDasharray="3 3" />
                                        <XAxis dataKey="month" />
                                        <YAxis />
                                        <Tooltip />
                                        <Legend />
                                        <Line type="monotone" dataKey="messages" name="Messages" stroke="#8b5cf6" />
                                        <Line type="monotone" dataKey="campaigns" name="Campagnes" stroke="#6366f1" />
                                    </LineChart>
                                </ResponsiveContainer>
                            </div>
                        </div>

                        {/* Category Distribution Chart */}
                        <div className="overflow-hidden rounded-lg bg-white p-6 shadow-lg">
                            <h3 className="font-playfair text-lg font-semibold text-gray-900">Distribution par Catégorie</h3>
                            <div className="mt-4 h-80">
                                <ResponsiveContainer width="100%" height="100%">
                                    <BarChart data={stats.categoryDistribution}>
                                        <CartesianGrid strokeDasharray="3 3" />
                                        <XAxis dataKey="name" />
                                        <YAxis />
                                        <Tooltip />
                                        <Legend />
                                        <Bar dataKey="count" name="Clients" fill="#8b5cf6" />
                                    </BarChart>
                                </ResponsiveContainer>
                            </div>
                        </div>
                    </div>

                    {/* Additional Stats */}
                    <div className="mt-8 overflow-hidden rounded-lg bg-white p-6 shadow-lg">
                        <h3 className="font-playfair text-lg font-semibold text-gray-900">Performance Globale</h3>
                        <div className="mt-4 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
                            <div className="rounded-lg bg-gradient-to-br from-violet-500 to-indigo-600 p-4 text-white">
                                <h4 className="font-montserrat text-sm font-medium">Messages ce Mois</h4>
                                <p className="font-playfair text-2xl font-semibold">{stats.messagesSentThisMonth}</p>
                            </div>
                            <div className="rounded-lg bg-gradient-to-br from-violet-500 to-indigo-600 p-4 text-white">
                                <h4 className="font-montserrat text-sm font-medium">Total Messages</h4>
                                <p className="font-playfair text-2xl font-semibold">{stats.totalMessages}</p>
                            </div>
                            <div className="rounded-lg bg-gradient-to-br from-violet-500 to-indigo-600 p-4 text-white">
                                <h4 className="font-montserrat text-sm font-medium">Taux de Livraison</h4>
                                <p className="font-playfair text-2xl font-semibold">{stats.deliveryRate}%</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </AuthenticatedLayout>
    );
}
